WITH
	TRATAMENTO_MARCA AS (
	SELECT 
	'ALIMENTOS-BEBIDAS' AS CATEGORIA
	,CASE
		WHEN MARCA LIKE '%Vitao%' THEN 'Vitao'	
		WHEN MARCA LIKE '%Luckau%' THEN 'Luckau'
		WHEN MARCA LIKE '%Haoma%' THEN 'Haoma'
		WHEN MARCA LIKE '%Da Magrinha%' THEN 'Da Magrinha'
		WHEN MARCA LIKE '%Puravida%' THEN 'Puravida'
		WHEN MARCA LIKE '%Bombay%' THEN 'Bombay'
		WHEN MARCA LIKE '%Flormel%' THEN 'Flormel'
		WHEN MARCA LIKE '%Fhom%' THEN 'Fhom'
		WHEN MARCA LIKE '%Bold Snacks%' THEN 'Bold Snacks'
		WHEN MARCA LIKE '%Mãe Terra%' THEN 'Mãe Terra'
		WHEN MARCA LIKE '%biO2%' THEN 'biO2'
		WHEN MARCA LIKE '%Suavipan%' THEN 'Suavipan'
		WHEN MARCA LIKE '%Belive%' THEN 'Belive'
		WHEN MARCA LIKE '%Schar%' THEN 'Schar'
		WHEN MARCA LIKE '%Warabu%' THEN 'Warabu'
		WHEN MARCA LIKE '%Mundo Verde%' THEN 'Mundo Verde'
		WHEN MARCA LIKE '%Stevita%' THEN 'Stevita'
		WHEN MARCA LIKE '%Chocolife%' THEN 'Chocolife'
		WHEN MARCA LIKE '%Sabor Alternati%' THEN 'Sabor Alternati'
		WHEN MARCA LIKE '%Essential Nutri%' THEN 'Essential Nutri'
		WHEN MARCA LIKE '%Wvegan%' THEN 'Wvegan'
		WHEN MARCA LIKE '%Mrs Taste%' THEN 'Mrs Taste'
		WHEN MARCA LIKE '%Mexidona%' THEN 'Mexidona'
		WHEN MARCA LIKE '%Mais Mu%' THEN 'Mais Mu'
		WHEN MARCA LIKE '%Life Mix%' THEN 'Life Mix'
		WHEN MARCA LIKE '%Eat Clean%' THEN 'Eat Clean'
		WHEN MARCA LIKE '%Engenho da Terr%' THEN 'Engenho da Terr'
		WHEN MARCA LIKE '%Caffeine Army%' THEN 'Caffeine Army'
		WHEN MARCA LIKE '%Papapá%' THEN 'Papapá'
		WHEN MARCA LIKE '%Pic-me%' THEN 'Pic-me'
		WHEN MARCA LIKE '%Canibal Inc%' THEN 'Canibal Inc'
		WHEN MARCA LIKE '%Aminna%' THEN 'Aminna'
		WHEN MARCA LIKE '%Grani Amici%' THEN 'Grani Amici'
		WHEN MARCA LIKE '%Fit Food%' THEN 'Fit Food'
		WHEN MARCA LIKE '%Mesmo!%' THEN 'Mesmo!'
		WHEN MARCA LIKE '%Atlhetica%' THEN 'Atlhetica'
		WHEN MARCA LIKE '%Integralmedica%' THEN 'Integralmedica'
		WHEN MARCA LIKE '%Casa Valentina%' THEN 'Casa Valentina'
		WHEN MARCA LIKE '%Vitapower%' THEN 'Vitapower'
		WHEN MARCA LIKE '%Naiak%' THEN 'Naiak'
		WHEN MARCA LIKE '%Tnuva%' THEN 'Tnuva'
		WHEN MARCA LIKE '%Roots to go%' THEN 'Roots to go'
		WHEN MARCA LIKE '%Mais Pura%' THEN 'Mais Pura'
		WHEN MARCA LIKE '%La Pianezza%' THEN 'La Pianezza'
		WHEN MARCA LIKE '%Desinchá%' THEN 'Desinchá'
		WHEN MARCA LIKE '%Super Nutrition%' THEN 'Super Nutrition'
		WHEN MARCA LIKE '%Nutrata%' THEN 'Nutrata'
		WHEN MARCA LIKE '%Mundo Verde Sel%' THEN 'Mundo Verde Sel'
		WHEN MARCA LIKE '%Castanharia%' THEN 'Castanharia'
		WHEN MARCA LIKE '%Alkimia%' THEN 'Alkimia'
		WHEN MARCA LIKE '%Oner%' THEN 'Oner'
		WHEN MARCA LIKE '%Naked Nuts%' THEN 'Naked Nuts'
		WHEN MARCA LIKE '%Nutrify%' THEN 'Nutrify'
		WHEN MARCA LIKE '%Espírito Cacau%' THEN 'Espírito Cacau'
		WHEN MARCA LIKE '%Vitafor%' THEN 'Vitafor'
		WHEN MARCA LIKE '%Dom Afonso%' THEN 'Dom Afonso'
		WHEN MARCA LIKE '%Banana Brasil%' THEN 'Banana Brasil'
		WHEN MARCA LIKE '%You Ka%' THEN 'You Ka'
		WHEN MARCA LIKE '%Super Vegan%' THEN 'Super Vegan'
		WHEN MARCA LIKE '%Snackout%' THEN 'Snackout'
		WHEN MARCA LIKE '%Amigos do Bem%' THEN 'Amigos do Bem'
		WHEN MARCA LIKE '%A Tal da Castan%' THEN 'A Tal da Castan'
		WHEN MARCA LIKE '%Uniagro%' THEN 'Uniagro'
		WHEN MARCA LIKE '%Monama%' THEN 'Monama'
		WHEN MARCA LIKE '%Chá Mais%' THEN 'Chá Mais'
		WHEN MARCA LIKE '%BetterPB%' THEN 'BetterPB'
		WHEN MARCA LIKE '%Betterlife%' THEN 'Betterlife'
		WHEN MARCA LIKE '%Beeva%' THEN 'Beeva'
		WHEN MARCA LIKE '%Alternativ%' THEN 'Alternativ'
		WHEN MARCA LIKE '%Nutrawell%' THEN 'Nutrawell'
		WHEN MARCA LIKE '%Nobrand%' THEN 'Nobrand'
		WHEN MARCA LIKE '%Mise%' THEN 'Mise'
		WHEN MARCA LIKE '%Koobi Kombucha%' THEN 'Koobi Kombucha'
		WHEN MARCA LIKE '%Konjac%' THEN 'Konjac'
		WHEN MARCA LIKE '%Darkness%' THEN 'Darkness'
		WHEN MARCA LIKE '%Ama Time%' THEN 'Ama Time'
		WHEN MARCA LIKE '%Advanced Nutrit%' THEN 'Advanced Nutrit'
		WHEN MARCA LIKE '%Sanavita%' THEN 'Sanavita'
		WHEN MARCA LIKE '%Power Focus%' THEN 'Power Focus'
		WHEN MARCA LIKE '%NotCo%' THEN 'NotCo'
		WHEN MARCA LIKE '%Magic Chocolate%' THEN 'Magic Chocolate'
		WHEN MARCA LIKE '%Linea%' THEN 'Linea'
		WHEN MARCA LIKE '%Estar Bem%' THEN 'Estar Bem'
		WHEN MARCA LIKE '%Danone%' THEN 'Danone'
		WHEN MARCA LIKE '%Da Roça%' THEN 'Da Roça'
		WHEN MARCA LIKE '%Brazô Alimentos%' THEN 'Brazô Alimentos'
		WHEN MARCA LIKE '%Plant Power%' THEN 'Plant Power'
		WHEN MARCA LIKE '%Mendoá%' THEN 'Mendoá'
		WHEN MARCA LIKE '%Leve Croc%' THEN 'Leve Croc'
		WHEN MARCA LIKE '%Holy Nuts%' THEN 'Holy Nuts'
		WHEN MARCA LIKE '%Good Soy%' THEN 'Good Soy'
		WHEN MARCA LIKE '%Chef Di Serio%' THEN 'Chef Di Serio'
		WHEN MARCA LIKE '%Wakas%' THEN 'Wakas'
		WHEN MARCA LIKE '%Valda%' THEN 'Valda'
		WHEN MARCA LIKE '%Fehe%' THEN 'Fehe'
		WHEN MARCA LIKE '%Chock%' THEN 'Chock'
		WHEN MARCA LIKE '%Chanical%' THEN 'Chanical'
		WHEN MARCA LIKE '%&Joy%' THEN '&Joy'
		WHEN MARCA LIKE '%Zen Foods%' THEN 'Zen Foods'
		WHEN MARCA LIKE '%Zaya%' THEN 'Zaya'
		WHEN MARCA LIKE '%Yamamotoyama%' THEN 'Yamamotoyama'
		WHEN MARCA LIKE '%Vitalin%' THEN 'Vitalin'
		WHEN MARCA LIKE '%Vital Âtman%' THEN 'Vital Âtman'
		WHEN MARCA LIKE '%Poder da Terra%' THEN 'Poder da Terra'
		WHEN MARCA LIKE '%Dose Coffee%' THEN 'Dose Coffee'
		WHEN MARCA LIKE '%Carob House%' THEN 'Carob House'
		WHEN MARCA LIKE '%Bananinha Palmi%' THEN 'Bananinha Palmi'
		WHEN MARCA LIKE '%Plant Pro%' THEN 'Plant Pro'
		WHEN MARCA LIKE '%Mare Chocolate%' THEN 'Mare Chocolate'
		WHEN MARCA LIKE '%Frontera%' THEN 'Frontera'
		WHEN MARCA LIKE '%Fini%' THEN 'Fini'
		WHEN MARCA LIKE '%Fiber%' THEN 'Fiber'
		WHEN MARCA LIKE '%Beladri%' THEN 'Beladri'
		WHEN MARCA LIKE '%Amma Chocolate%' THEN 'Amma Chocolate'
		WHEN MARCA LIKE '%True Source%' THEN 'True Source'
		WHEN MARCA LIKE '%Tivva%' THEN 'Tivva'
		WHEN MARCA LIKE '%Terra Moriá%' THEN 'Terra Moriá'
		WHEN MARCA LIKE '%Organique%' THEN 'Organique'
		WHEN MARCA LIKE '%Omix%' THEN 'Omix'
		WHEN MARCA LIKE '%Nutríssima%' THEN 'Nutríssima'
		WHEN MARCA LIKE '%Moderação%' THEN 'Moderação'
		WHEN MARCA LIKE '%Harts Natural%' THEN 'Harts Natural'
		WHEN MARCA LIKE '%Fresh Nutrition%' THEN 'Fresh Nutrition'
		WHEN MARCA LIKE '%Dobro%' THEN 'Dobro'
		WHEN MARCA LIKE '%Crilancha%' THEN 'Crilancha'
		WHEN MARCA LIKE '%Copra Coco%' THEN 'Copra Coco'
		WHEN MARCA LIKE '%Sweet Jelly%' THEN 'Sweet Jelly'
		WHEN MARCA LIKE '%Planttcê%' THEN 'Planttcê'
		WHEN MARCA LIKE '%Pipoca do Johnn%' THEN 'Pipoca do Johnn'
		WHEN MARCA LIKE '%Ocean Drop%' THEN 'Ocean Drop'
		WHEN MARCA LIKE '%Natures Heart%' THEN 'Natures Heart'
		WHEN MARCA LIKE '%Mundo Verde Eli%' THEN 'Mundo Verde Eli'
		WHEN MARCA LIKE '%Mais Mu Perform%' THEN 'Mais Mu Perform'
		WHEN MARCA LIKE '%Macrokant%' THEN 'Macrokant'
		WHEN MARCA LIKE '%Kim Zucateli%' THEN 'Kim Zucateli'
		WHEN MARCA LIKE '%Iridium Labs%' THEN 'Iridium Labs'
		WHEN MARCA LIKE '%Hypera Pharma%' THEN 'Hypera Pharma'
		WHEN MARCA LIKE '%Ecobio%' THEN 'Ecobio'
		WHEN MARCA LIKE '%Chá Prenda%' THEN 'Chá Prenda'
		WHEN MARCA LIKE '%100% Você%' THEN '100% Você'
		WHEN MARCA LIKE '%Zucca Cogumelos%' THEN 'Zucca Cogumelos'
		WHEN MARCA LIKE '%Ws Naturais%' THEN 'Ws Naturais'
		WHEN MARCA LIKE '%Onvittá%' THEN 'Onvittá'
		WHEN MARCA LIKE '%Natures Heart%' THEN 'Natures Heart'
		WHEN MARCA LIKE '%Mellow%' THEN 'Mellow'
		WHEN MARCA LIKE '%Jungle%' THEN 'Jungle'
		WHEN MARCA LIKE '%Ganic%' THEN 'Ganic'
		WHEN MARCA LIKE '%Dêvi%' THEN 'Dêvi'
		WHEN MARCA LIKE '%Crystal Sweet%' THEN 'Crystal Sweet'
		WHEN MARCA LIKE '%Café Utam%' THEN 'Café Utam'
		WHEN MARCA LIKE '%Bioroots%' THEN 'Bioroots'
		WHEN MARCA LIKE '%Airon%' THEN 'Airon'
		WHEN MARCA LIKE '%Vida Veg%' THEN 'Vida Veg'
		WHEN MARCA LIKE '%Upnutri%' THEN 'Upnutri'
		WHEN MARCA LIKE '%Sesamo Real%' THEN 'Sesamo Real'
		WHEN MARCA LIKE '%QueenNut%' THEN 'QueenNut'
		WHEN MARCA LIKE '%Piracanjuba%' THEN 'Piracanjuba'
		WHEN MARCA LIKE '%Pinati%' THEN 'Pinati'
		WHEN MARCA LIKE '%Pholias%' THEN 'Pholias'
		WHEN MARCA LIKE '%Nutraway%' THEN 'Nutraway'
		WHEN MARCA LIKE '%Naturalis%' THEN 'Naturalis'
		WHEN MARCA LIKE '%Lowçucar%' THEN 'Lowçucar'
		WHEN MARCA LIKE '%Kur Kur%' THEN 'Kur Kur'
		WHEN MARCA LIKE '%Kur%' THEN 'Kur Kur'
		WHEN MARCA LIKE '%Kur My Home Spa%' THEN 'Kur My Home Spa'
		WHEN MARCA LIKE '%Java Chocolates%' THEN 'Java Chocolates'
		WHEN MARCA LIKE '%Gummy%' THEN 'Gummy'
		WHEN MARCA LIKE '%Gaab%' THEN 'Gaab'
		WHEN MARCA LIKE '%Fumel%' THEN 'Fumel'
		WHEN MARCA LIKE '%Bifum%' THEN 'Bifum'
		WHEN MARCA LIKE '%Agtal%' THEN 'Agtal'
		WHEN MARCA LIKE '%Ayurveda%' THEN 'Kim Zucateli'
		WHEN MARCA LIKE '%DESINCHÁ%' THEN  'Desinchá'
		WHEN MARCA LIKE 'DESIN%' THEN  'Desinchá'
		WHEN MARCA LIKE 'Chá da Frozen Frutas Vermelhas 15sch 22,5g' THEN 'Desinchá'
		WHEN MARCA = 'Geleia Zero Uva 180g' THEN  'Vitao'
		WHEN MARCA = 'Manjar Coco Vegano em pó 50g Herbalmedica' THEN  'Wvegan'
		WHEN MARCA LIKE '%Hart''s Natural%' THEN 'Hart''s Natural'
		WHEN MARCA = 'Barra Choco ao Leite Zero Poliol com Pedaços de Pistache 75g' THEN  'LUCKAU'
		ELSE 'OUTROS'
	END AS MARCA_PRODUTO, * 

	FROM 
		ST_PRODUTO_PRECO_MV_DETALHADO

UNION ALL

SELECT 
	'SUPLEMENTOS' AS CATEGORIA
	,CASE
		WHEN MARCA LIKE '%Vitao%' THEN 'Vitao'	
		WHEN MARCA LIKE '%Luckau%' THEN 'Luckau'
		WHEN MARCA LIKE '%Haoma%' THEN 'Haoma'
		WHEN MARCA LIKE '%Da Magrinha%' THEN 'Da Magrinha'
		WHEN MARCA LIKE '%Puravida%' THEN 'Puravida'
		WHEN MARCA LIKE '%Bombay%' THEN 'Bombay'
		WHEN MARCA LIKE '%Flormel%' THEN 'Flormel'
		WHEN MARCA LIKE '%Fhom%' THEN 'Fhom'
		WHEN MARCA LIKE '%Bold Snacks%' THEN 'Bold Snacks'
		WHEN MARCA LIKE '%Mãe Terra%' THEN 'Mãe Terra'
		WHEN MARCA LIKE '%biO2%' THEN 'biO2'
		WHEN MARCA LIKE '%Suavipan%' THEN 'Suavipan'
		WHEN MARCA LIKE '%Belive%' THEN 'Belive'
		WHEN MARCA LIKE '%Schar%' THEN 'Schar'
		WHEN MARCA LIKE '%Warabu%' THEN 'Warabu'
		WHEN MARCA LIKE '%Mundo Verde%' THEN 'Mundo Verde'
		WHEN MARCA LIKE '%Stevita%' THEN 'Stevita'
		WHEN MARCA LIKE '%Chocolife%' THEN 'Chocolife'
		WHEN MARCA LIKE '%Sabor Alternati%' THEN 'Sabor Alternati'
		WHEN MARCA LIKE '%Essential Nutri%' THEN 'Essential Nutri'
		WHEN MARCA LIKE '%Wvegan%' THEN 'Wvegan'
		WHEN MARCA LIKE '%Mrs Taste%' THEN 'Mrs Taste'
		WHEN MARCA LIKE '%Mexidona%' THEN 'Mexidona'
		WHEN MARCA LIKE '%Mais Mu%' THEN 'Mais Mu'
		WHEN MARCA LIKE '%Life Mix%' THEN 'Life Mix'
		WHEN MARCA LIKE '%Eat Clean%' THEN 'Eat Clean'
		WHEN MARCA LIKE '%Engenho da Terr%' THEN 'Engenho da Terr'
		WHEN MARCA LIKE '%Caffeine Army%' THEN 'Caffeine Army'
		WHEN MARCA LIKE '%Papapá%' THEN 'Papapá'
		WHEN MARCA LIKE '%Pic-me%' THEN 'Pic-me'
		WHEN MARCA LIKE '%Canibal Inc%' THEN 'Canibal Inc'
		WHEN MARCA LIKE '%Aminna%' THEN 'Aminna'
		WHEN MARCA LIKE '%Grani Amici%' THEN 'Grani Amici'
		WHEN MARCA LIKE '%Fit Food%' THEN 'Fit Food'
		WHEN MARCA LIKE '%Mesmo!%' THEN 'Mesmo!'
		WHEN MARCA LIKE '%Atlhetica%' THEN 'Atlhetica'
		WHEN MARCA LIKE '%Integralmedica%' THEN 'Integralmedica'
		WHEN MARCA LIKE '%Casa Valentina%' THEN 'Casa Valentina'
		WHEN MARCA LIKE '%Vitapower%' THEN 'Vitapower'
		WHEN MARCA LIKE '%Naiak%' THEN 'Naiak'
		WHEN MARCA LIKE '%Tnuva%' THEN 'Tnuva'
		WHEN MARCA LIKE '%Roots to go%' THEN 'Roots to go'
		WHEN MARCA LIKE '%Mais Pura%' THEN 'Mais Pura'
		WHEN MARCA LIKE '%La Pianezza%' THEN 'La Pianezza'
		WHEN MARCA LIKE '%Desinchá%' THEN 'Desinchá'
		WHEN MARCA LIKE '%Super Nutrition%' THEN 'Super Nutrition'
		WHEN MARCA LIKE '%Nutrata%' THEN 'Nutrata'
		WHEN MARCA LIKE '%Mundo Verde Sel%' THEN 'Mundo Verde Sel'
		WHEN MARCA LIKE '%Castanharia%' THEN 'Castanharia'
		WHEN MARCA LIKE '%Alkimia%' THEN 'Alkimia'
		WHEN MARCA LIKE '%Oner%' THEN 'Oner'
		WHEN MARCA LIKE '%Naked Nuts%' THEN 'Naked Nuts'
		WHEN MARCA LIKE '%Nutrify%' THEN 'Nutrify'
		WHEN MARCA LIKE '%Espírito Cacau%' THEN 'Espírito Cacau'
		WHEN MARCA LIKE '%Vitafor%' THEN 'Vitafor'
		WHEN MARCA LIKE '%Dom Afonso%' THEN 'Dom Afonso'
		WHEN MARCA LIKE '%Banana Brasil%' THEN 'Banana Brasil'
		WHEN MARCA LIKE '%You Ka%' THEN 'You Ka'
		WHEN MARCA LIKE '%Super Vegan%' THEN 'Super Vegan'
		WHEN MARCA LIKE '%Snackout%' THEN 'Snackout'
		WHEN MARCA LIKE '%Amigos do Bem%' THEN 'Amigos do Bem'
		WHEN MARCA LIKE '%A Tal da Castan%' THEN 'A Tal da Castan'
		WHEN MARCA LIKE '%Uniagro%' THEN 'Uniagro'
		WHEN MARCA LIKE '%Monama%' THEN 'Monama'
		WHEN MARCA LIKE '%Chá Mais%' THEN 'Chá Mais'
		WHEN MARCA LIKE '%BetterPB%' THEN 'BetterPB'
		WHEN MARCA LIKE '%Betterlife%' THEN 'Betterlife'
		WHEN MARCA LIKE '%Beeva%' THEN 'Beeva'
		WHEN MARCA LIKE '%Alternativ%' THEN 'Alternativ'
		WHEN MARCA LIKE '%Nutrawell%' THEN 'Nutrawell'
		WHEN MARCA LIKE '%Nobrand%' THEN 'Nobrand'
		WHEN MARCA LIKE '%Mise%' THEN 'Mise'
		WHEN MARCA LIKE '%Koobi Kombucha%' THEN 'Koobi Kombucha'
		WHEN MARCA LIKE '%Konjac%' THEN 'Konjac'
		WHEN MARCA LIKE '%Darkness%' THEN 'Darkness'
		WHEN MARCA LIKE '%Ama Time%' THEN 'Ama Time'
		WHEN MARCA LIKE '%Advanced Nutrit%' THEN 'Advanced Nutrit'
		WHEN MARCA LIKE '%Sanavita%' THEN 'Sanavita'
		WHEN MARCA LIKE '%Power Focus%' THEN 'Power Focus'
		WHEN MARCA LIKE '%NotCo%' THEN 'NotCo'
		WHEN MARCA LIKE '%Magic Chocolate%' THEN 'Magic Chocolate'
		WHEN MARCA LIKE '%Linea%' THEN 'Linea'
		WHEN MARCA LIKE '%Estar Bem%' THEN 'Estar Bem'
		WHEN MARCA LIKE '%Danone%' THEN 'Danone'
		WHEN MARCA LIKE '%Da Roça%' THEN 'Da Roça'
		WHEN MARCA LIKE '%Brazô Alimentos%' THEN 'Brazô Alimentos'
		WHEN MARCA LIKE '%Plant Power%' THEN 'Plant Power'
		WHEN MARCA LIKE '%Mendoá%' THEN 'Mendoá'
		WHEN MARCA LIKE '%Leve Croc%' THEN 'Leve Croc'
		WHEN MARCA LIKE '%Holy Nuts%' THEN 'Holy Nuts'
		WHEN MARCA LIKE '%Good Soy%' THEN 'Good Soy'
		WHEN MARCA LIKE '%Chef Di Serio%' THEN 'Chef Di Serio'
		WHEN MARCA LIKE '%Wakas%' THEN 'Wakas'
		WHEN MARCA LIKE '%Valda%' THEN 'Valda'
		WHEN MARCA LIKE '%Fehe%' THEN 'Fehe'
		WHEN MARCA LIKE '%Chock%' THEN 'Chock'
		WHEN MARCA LIKE '%Chanical%' THEN 'Chanical'
		WHEN MARCA LIKE '%&Joy%' THEN '&Joy'
		WHEN MARCA LIKE '%Zen Foods%' THEN 'Zen Foods'
		WHEN MARCA LIKE '%Zaya%' THEN 'Zaya'
		WHEN MARCA LIKE '%Yamamotoyama%' THEN 'Yamamotoyama'
		WHEN MARCA LIKE '%Vitalin%' THEN 'Vitalin'
		WHEN MARCA LIKE '%Vital Âtman%' THEN 'Vital Âtman'
		WHEN MARCA LIKE '%Poder da Terra%' THEN 'Poder da Terra'
		WHEN MARCA LIKE '%Dose Coffee%' THEN 'Dose Coffee'
		WHEN MARCA LIKE '%Carob House%' THEN 'Carob House'
		WHEN MARCA LIKE '%Bananinha Palmi%' THEN 'Bananinha Palmi'
		WHEN MARCA LIKE '%Plant Pro%' THEN 'Plant Pro'
		WHEN MARCA LIKE '%Mare Chocolate%' THEN 'Mare Chocolate'
		WHEN MARCA LIKE '%Frontera%' THEN 'Frontera'
		WHEN MARCA LIKE '%Fini%' THEN 'Fini'
		WHEN MARCA LIKE '%Fiber%' THEN 'Fiber'
		WHEN MARCA LIKE '%Beladri%' THEN 'Beladri'
		WHEN MARCA LIKE '%Amma Chocolate%' THEN 'Amma Chocolate'
		WHEN MARCA LIKE '%True Source%' THEN 'True Source'
		WHEN MARCA LIKE '%Tivva%' THEN 'Tivva'
		WHEN MARCA LIKE '%Terra Moriá%' THEN 'Terra Moriá'
		WHEN MARCA LIKE '%Organique%' THEN 'Organique'
		WHEN MARCA LIKE '%Omix%' THEN 'Omix'
		WHEN MARCA LIKE '%Nutríssima%' THEN 'Nutríssima'
		WHEN MARCA LIKE '%Moderação%' THEN 'Moderação'
		WHEN MARCA LIKE '%Harts Natural%' THEN 'Harts Natural'
		WHEN MARCA LIKE '%Fresh Nutrition%' THEN 'Fresh Nutrition'
		WHEN MARCA LIKE '%Dobro%' THEN 'Dobro'
		WHEN MARCA LIKE '%Crilancha%' THEN 'Crilancha'
		WHEN MARCA LIKE '%Copra Coco%' THEN 'Copra Coco'
		WHEN MARCA LIKE '%Sweet Jelly%' THEN 'Sweet Jelly'
		WHEN MARCA LIKE '%Planttcê%' THEN 'Planttcê'
		WHEN MARCA LIKE '%Pipoca do Johnn%' THEN 'Pipoca do Johnn'
		WHEN MARCA LIKE '%Ocean Drop%' THEN 'Ocean Drop'
		WHEN MARCA LIKE '%Natures Heart%' THEN 'Natures Heart'
		WHEN MARCA LIKE '%Mundo Verde Eli%' THEN 'Mundo Verde Eli'
		WHEN MARCA LIKE '%Mais Mu Perform%' THEN 'Mais Mu Perform'
		WHEN MARCA LIKE '%Macrokant%' THEN 'Macrokant'
		WHEN MARCA LIKE '%Kim Zucateli%' THEN 'Kim Zucateli'
		WHEN MARCA LIKE '%Iridium Labs%' THEN 'Iridium Labs'
		WHEN MARCA LIKE '%Hypera Pharma%' THEN 'Hypera Pharma'
		WHEN MARCA LIKE '%Ecobio%' THEN 'Ecobio'
		WHEN MARCA LIKE '%Chá Prenda%' THEN 'Chá Prenda'
		WHEN MARCA LIKE '%100% Você%' THEN '100% Você'
		WHEN MARCA LIKE '%Zucca Cogumelos%' THEN 'Zucca Cogumelos'
		WHEN MARCA LIKE '%Ws Naturais%' THEN 'Ws Naturais'
		WHEN MARCA LIKE '%Onvittá%' THEN 'Onvittá'
		WHEN MARCA LIKE '%Natures Heart%' THEN 'Natures Heart'
		WHEN MARCA LIKE '%Mellow%' THEN 'Mellow'
		WHEN MARCA LIKE '%Jungle%' THEN 'Jungle'
		WHEN MARCA LIKE '%Ganic%' THEN 'Ganic'
		WHEN MARCA LIKE '%Dêvi%' THEN 'Dêvi'
		WHEN MARCA LIKE '%Crystal Sweet%' THEN 'Crystal Sweet'
		WHEN MARCA LIKE '%Café Utam%' THEN 'Café Utam'
		WHEN MARCA LIKE '%Bioroots%' THEN 'Bioroots'
		WHEN MARCA LIKE '%Airon%' THEN 'Airon'
		WHEN MARCA LIKE '%Vida Veg%' THEN 'Vida Veg'
		WHEN MARCA LIKE '%Upnutri%' THEN 'Upnutri'
		WHEN MARCA LIKE '%Sesamo Real%' THEN 'Sesamo Real'
		WHEN MARCA LIKE '%QueenNut%' THEN 'QueenNut'
		WHEN MARCA LIKE '%Piracanjuba%' THEN 'Piracanjuba'
		WHEN MARCA LIKE '%Pinati%' THEN 'Pinati'
		WHEN MARCA LIKE '%Pholias%' THEN 'Pholias'
		WHEN MARCA LIKE '%Nutraway%' THEN 'Nutraway'
		WHEN MARCA LIKE '%Naturalis%' THEN 'Naturalis'
		WHEN MARCA LIKE '%Lowçucar%' THEN 'Lowçucar'
		WHEN MARCA LIKE '%Kur Kur%' THEN 'Kur Kur'
		WHEN MARCA LIKE '%Kur%' THEN 'Kur Kur'
		WHEN MARCA LIKE '%Kur My Home Spa%' THEN 'Kur My Home Spa'
		WHEN MARCA LIKE '%Java Chocolates%' THEN 'Java Chocolates'
		WHEN MARCA LIKE '%Gummy%' THEN 'Gummy'
		WHEN MARCA LIKE '%Gaab%' THEN 'Gaab'
		WHEN MARCA LIKE '%Fumel%' THEN 'Fumel'
		WHEN MARCA LIKE '%Bifum%' THEN 'Bifum'
		WHEN MARCA LIKE '%Agtal%' THEN 'Agtal'
		WHEN MARCA LIKE '%Ayurveda%' THEN 'Kim Zucateli'
		WHEN MARCA LIKE '%DESINCHÁ%' THEN  'Desinchá'
		WHEN MARCA LIKE 'DESIN%' THEN  'Desinchá'
		WHEN MARCA LIKE 'Chá da Frozen Frutas Vermelhas 15sch 22,5g' THEN 'Desinchá'
		WHEN MARCA = 'Geleia Zero Uva 180g' THEN  'Vitao'
		WHEN MARCA = 'Manjar Coco Vegano em pó 50g Herbalmedica' THEN  'Wvegan'
		WHEN MARCA LIKE '%Hart''s Natural%' THEN 'Hart''s Natural'
		WHEN MARCA = 'Barra Choco ao Leite Zero Poliol com Pedaços de Pistache 75g' THEN  'LUCKAU'
		ELSE 'OUTROS'
	END AS MARCA_PRODUTO, * 

	FROM 
		ST_PRODUTO_PRECO_MV_DETALHADO_SUPLEMENTO

UNION ALL

SELECT 
	'OFERTAS' AS CATEGORIA
	,CASE
		WHEN MARCA LIKE '%Vitao%' THEN 'Vitao'	
		WHEN MARCA LIKE '%Luckau%' THEN 'Luckau'
		WHEN MARCA LIKE '%Haoma%' THEN 'Haoma'
		WHEN MARCA LIKE '%Da Magrinha%' THEN 'Da Magrinha'
		WHEN MARCA LIKE '%Puravida%' THEN 'Puravida'
		WHEN MARCA LIKE '%Bombay%' THEN 'Bombay'
		WHEN MARCA LIKE '%Flormel%' THEN 'Flormel'
		WHEN MARCA LIKE '%Fhom%' THEN 'Fhom'
		WHEN MARCA LIKE '%Bold Snacks%' THEN 'Bold Snacks'
		WHEN MARCA LIKE '%Mãe Terra%' THEN 'Mãe Terra'
		WHEN MARCA LIKE '%biO2%' THEN 'biO2'
		WHEN MARCA LIKE '%Suavipan%' THEN 'Suavipan'
		WHEN MARCA LIKE '%Belive%' THEN 'Belive'
		WHEN MARCA LIKE '%Schar%' THEN 'Schar'
		WHEN MARCA LIKE '%Warabu%' THEN 'Warabu'
		WHEN MARCA LIKE '%Mundo Verde%' THEN 'Mundo Verde'
		WHEN MARCA LIKE '%Stevita%' THEN 'Stevita'
		WHEN MARCA LIKE '%Chocolife%' THEN 'Chocolife'
		WHEN MARCA LIKE '%Sabor Alternati%' THEN 'Sabor Alternati'
		WHEN MARCA LIKE '%Essential Nutri%' THEN 'Essential Nutri'
		WHEN MARCA LIKE '%Wvegan%' THEN 'Wvegan'
		WHEN MARCA LIKE '%Mrs Taste%' THEN 'Mrs Taste'
		WHEN MARCA LIKE '%Mexidona%' THEN 'Mexidona'
		WHEN MARCA LIKE '%Mais Mu%' THEN 'Mais Mu'
		WHEN MARCA LIKE '%Life Mix%' THEN 'Life Mix'
		WHEN MARCA LIKE '%Eat Clean%' THEN 'Eat Clean'
		WHEN MARCA LIKE '%Engenho da Terr%' THEN 'Engenho da Terr'
		WHEN MARCA LIKE '%Caffeine Army%' THEN 'Caffeine Army'
		WHEN MARCA LIKE '%Papapá%' THEN 'Papapá'
		WHEN MARCA LIKE '%Pic-me%' THEN 'Pic-me'
		WHEN MARCA LIKE '%Canibal Inc%' THEN 'Canibal Inc'
		WHEN MARCA LIKE '%Aminna%' THEN 'Aminna'
		WHEN MARCA LIKE '%Grani Amici%' THEN 'Grani Amici'
		WHEN MARCA LIKE '%Fit Food%' THEN 'Fit Food'
		WHEN MARCA LIKE '%Mesmo!%' THEN 'Mesmo!'
		WHEN MARCA LIKE '%Atlhetica%' THEN 'Atlhetica'
		WHEN MARCA LIKE '%Integralmedica%' THEN 'Integralmedica'
		WHEN MARCA LIKE '%Casa Valentina%' THEN 'Casa Valentina'
		WHEN MARCA LIKE '%Vitapower%' THEN 'Vitapower'
		WHEN MARCA LIKE '%Naiak%' THEN 'Naiak'
		WHEN MARCA LIKE '%Tnuva%' THEN 'Tnuva'
		WHEN MARCA LIKE '%Roots to go%' THEN 'Roots to go'
		WHEN MARCA LIKE '%Mais Pura%' THEN 'Mais Pura'
		WHEN MARCA LIKE '%La Pianezza%' THEN 'La Pianezza'
		WHEN MARCA LIKE '%Desinchá%' THEN 'Desinchá'
		WHEN MARCA LIKE '%Super Nutrition%' THEN 'Super Nutrition'
		WHEN MARCA LIKE '%Nutrata%' THEN 'Nutrata'
		WHEN MARCA LIKE '%Mundo Verde Sel%' THEN 'Mundo Verde Sel'
		WHEN MARCA LIKE '%Castanharia%' THEN 'Castanharia'
		WHEN MARCA LIKE '%Alkimia%' THEN 'Alkimia'
		WHEN MARCA LIKE '%Oner%' THEN 'Oner'
		WHEN MARCA LIKE '%Naked Nuts%' THEN 'Naked Nuts'
		WHEN MARCA LIKE '%Nutrify%' THEN 'Nutrify'
		WHEN MARCA LIKE '%Espírito Cacau%' THEN 'Espírito Cacau'
		WHEN MARCA LIKE '%Vitafor%' THEN 'Vitafor'
		WHEN MARCA LIKE '%Dom Afonso%' THEN 'Dom Afonso'
		WHEN MARCA LIKE '%Banana Brasil%' THEN 'Banana Brasil'
		WHEN MARCA LIKE '%You Ka%' THEN 'You Ka'
		WHEN MARCA LIKE '%Super Vegan%' THEN 'Super Vegan'
		WHEN MARCA LIKE '%Snackout%' THEN 'Snackout'
		WHEN MARCA LIKE '%Amigos do Bem%' THEN 'Amigos do Bem'
		WHEN MARCA LIKE '%A Tal da Castan%' THEN 'A Tal da Castan'
		WHEN MARCA LIKE '%Uniagro%' THEN 'Uniagro'
		WHEN MARCA LIKE '%Monama%' THEN 'Monama'
		WHEN MARCA LIKE '%Chá Mais%' THEN 'Chá Mais'
		WHEN MARCA LIKE '%BetterPB%' THEN 'BetterPB'
		WHEN MARCA LIKE '%Betterlife%' THEN 'Betterlife'
		WHEN MARCA LIKE '%Beeva%' THEN 'Beeva'
		WHEN MARCA LIKE '%Alternativ%' THEN 'Alternativ'
		WHEN MARCA LIKE '%Nutrawell%' THEN 'Nutrawell'
		WHEN MARCA LIKE '%Nobrand%' THEN 'Nobrand'
		WHEN MARCA LIKE '%Mise%' THEN 'Mise'
		WHEN MARCA LIKE '%Koobi Kombucha%' THEN 'Koobi Kombucha'
		WHEN MARCA LIKE '%Konjac%' THEN 'Konjac'
		WHEN MARCA LIKE '%Darkness%' THEN 'Darkness'
		WHEN MARCA LIKE '%Ama Time%' THEN 'Ama Time'
		WHEN MARCA LIKE '%Advanced Nutrit%' THEN 'Advanced Nutrit'
		WHEN MARCA LIKE '%Sanavita%' THEN 'Sanavita'
		WHEN MARCA LIKE '%Power Focus%' THEN 'Power Focus'
		WHEN MARCA LIKE '%NotCo%' THEN 'NotCo'
		WHEN MARCA LIKE '%Magic Chocolate%' THEN 'Magic Chocolate'
		WHEN MARCA LIKE '%Linea%' THEN 'Linea'
		WHEN MARCA LIKE '%Estar Bem%' THEN 'Estar Bem'
		WHEN MARCA LIKE '%Danone%' THEN 'Danone'
		WHEN MARCA LIKE '%Da Roça%' THEN 'Da Roça'
		WHEN MARCA LIKE '%Brazô Alimentos%' THEN 'Brazô Alimentos'
		WHEN MARCA LIKE '%Plant Power%' THEN 'Plant Power'
		WHEN MARCA LIKE '%Mendoá%' THEN 'Mendoá'
		WHEN MARCA LIKE '%Leve Croc%' THEN 'Leve Croc'
		WHEN MARCA LIKE '%Holy Nuts%' THEN 'Holy Nuts'
		WHEN MARCA LIKE '%Good Soy%' THEN 'Good Soy'
		WHEN MARCA LIKE '%Chef Di Serio%' THEN 'Chef Di Serio'
		WHEN MARCA LIKE '%Wakas%' THEN 'Wakas'
		WHEN MARCA LIKE '%Valda%' THEN 'Valda'
		WHEN MARCA LIKE '%Fehe%' THEN 'Fehe'
		WHEN MARCA LIKE '%Chock%' THEN 'Chock'
		WHEN MARCA LIKE '%Chanical%' THEN 'Chanical'
		WHEN MARCA LIKE '%&Joy%' THEN '&Joy'
		WHEN MARCA LIKE '%Zen Foods%' THEN 'Zen Foods'
		WHEN MARCA LIKE '%Zaya%' THEN 'Zaya'
		WHEN MARCA LIKE '%Yamamotoyama%' THEN 'Yamamotoyama'
		WHEN MARCA LIKE '%Vitalin%' THEN 'Vitalin'
		WHEN MARCA LIKE '%Vital Âtman%' THEN 'Vital Âtman'
		WHEN MARCA LIKE '%Poder da Terra%' THEN 'Poder da Terra'
		WHEN MARCA LIKE '%Dose Coffee%' THEN 'Dose Coffee'
		WHEN MARCA LIKE '%Carob House%' THEN 'Carob House'
		WHEN MARCA LIKE '%Bananinha Palmi%' THEN 'Bananinha Palmi'
		WHEN MARCA LIKE '%Plant Pro%' THEN 'Plant Pro'
		WHEN MARCA LIKE '%Mare Chocolate%' THEN 'Mare Chocolate'
		WHEN MARCA LIKE '%Frontera%' THEN 'Frontera'
		WHEN MARCA LIKE '%Fini%' THEN 'Fini'
		WHEN MARCA LIKE '%Fiber%' THEN 'Fiber'
		WHEN MARCA LIKE '%Beladri%' THEN 'Beladri'
		WHEN MARCA LIKE '%Amma Chocolate%' THEN 'Amma Chocolate'
		WHEN MARCA LIKE '%True Source%' THEN 'True Source'
		WHEN MARCA LIKE '%Tivva%' THEN 'Tivva'
		WHEN MARCA LIKE '%Terra Moriá%' THEN 'Terra Moriá'
		WHEN MARCA LIKE '%Organique%' THEN 'Organique'
		WHEN MARCA LIKE '%Omix%' THEN 'Omix'
		WHEN MARCA LIKE '%Nutríssima%' THEN 'Nutríssima'
		WHEN MARCA LIKE '%Moderação%' THEN 'Moderação'
		WHEN MARCA LIKE '%Harts Natural%' THEN 'Harts Natural'
		WHEN MARCA LIKE '%Fresh Nutrition%' THEN 'Fresh Nutrition'
		WHEN MARCA LIKE '%Dobro%' THEN 'Dobro'
		WHEN MARCA LIKE '%Crilancha%' THEN 'Crilancha'
		WHEN MARCA LIKE '%Copra Coco%' THEN 'Copra Coco'
		WHEN MARCA LIKE '%Sweet Jelly%' THEN 'Sweet Jelly'
		WHEN MARCA LIKE '%Planttcê%' THEN 'Planttcê'
		WHEN MARCA LIKE '%Pipoca do Johnn%' THEN 'Pipoca do Johnn'
		WHEN MARCA LIKE '%Ocean Drop%' THEN 'Ocean Drop'
		WHEN MARCA LIKE '%Natures Heart%' THEN 'Natures Heart'
		WHEN MARCA LIKE '%Mundo Verde Eli%' THEN 'Mundo Verde Eli'
		WHEN MARCA LIKE '%Mais Mu Perform%' THEN 'Mais Mu Perform'
		WHEN MARCA LIKE '%Macrokant%' THEN 'Macrokant'
		WHEN MARCA LIKE '%Kim Zucateli%' THEN 'Kim Zucateli'
		WHEN MARCA LIKE '%Iridium Labs%' THEN 'Iridium Labs'
		WHEN MARCA LIKE '%Hypera Pharma%' THEN 'Hypera Pharma'
		WHEN MARCA LIKE '%Ecobio%' THEN 'Ecobio'
		WHEN MARCA LIKE '%Chá Prenda%' THEN 'Chá Prenda'
		WHEN MARCA LIKE '%100% Você%' THEN '100% Você'
		WHEN MARCA LIKE '%Zucca Cogumelos%' THEN 'Zucca Cogumelos'
		WHEN MARCA LIKE '%Ws Naturais%' THEN 'Ws Naturais'
		WHEN MARCA LIKE '%Onvittá%' THEN 'Onvittá'
		WHEN MARCA LIKE '%Natures Heart%' THEN 'Natures Heart'
		WHEN MARCA LIKE '%Mellow%' THEN 'Mellow'
		WHEN MARCA LIKE '%Jungle%' THEN 'Jungle'
		WHEN MARCA LIKE '%Ganic%' THEN 'Ganic'
		WHEN MARCA LIKE '%Dêvi%' THEN 'Dêvi'
		WHEN MARCA LIKE '%Crystal Sweet%' THEN 'Crystal Sweet'
		WHEN MARCA LIKE '%Café Utam%' THEN 'Café Utam'
		WHEN MARCA LIKE '%Bioroots%' THEN 'Bioroots'
		WHEN MARCA LIKE '%Airon%' THEN 'Airon'
		WHEN MARCA LIKE '%Vida Veg%' THEN 'Vida Veg'
		WHEN MARCA LIKE '%Upnutri%' THEN 'Upnutri'
		WHEN MARCA LIKE '%Sesamo Real%' THEN 'Sesamo Real'
		WHEN MARCA LIKE '%QueenNut%' THEN 'QueenNut'
		WHEN MARCA LIKE '%Piracanjuba%' THEN 'Piracanjuba'
		WHEN MARCA LIKE '%Pinati%' THEN 'Pinati'
		WHEN MARCA LIKE '%Pholias%' THEN 'Pholias'
		WHEN MARCA LIKE '%Nutraway%' THEN 'Nutraway'
		WHEN MARCA LIKE '%Naturalis%' THEN 'Naturalis'
		WHEN MARCA LIKE '%Lowçucar%' THEN 'Lowçucar'
		WHEN MARCA LIKE '%Kur Kur%' THEN 'Kur Kur'
		WHEN MARCA LIKE '%Kur%' THEN 'Kur Kur'
		WHEN MARCA LIKE '%Kur My Home Spa%' THEN 'Kur My Home Spa'
		WHEN MARCA LIKE '%Java Chocolates%' THEN 'Java Chocolates'
		WHEN MARCA LIKE '%Gummy%' THEN 'Gummy'
		WHEN MARCA LIKE '%Gaab%' THEN 'Gaab'
		WHEN MARCA LIKE '%Fumel%' THEN 'Fumel'
		WHEN MARCA LIKE '%Bifum%' THEN 'Bifum'
		WHEN MARCA LIKE '%Agtal%' THEN 'Agtal'
		WHEN MARCA LIKE '%Ayurveda%' THEN 'Kim Zucateli'
		WHEN MARCA LIKE '%DESINCHÁ%' THEN  'Desinchá'
		WHEN MARCA LIKE 'DESIN%' THEN  'Desinchá'
		WHEN MARCA LIKE 'Chá da Frozen Frutas Vermelhas 15sch 22,5g' THEN 'Desinchá'
		WHEN MARCA = 'Geleia Zero Uva 180g' THEN  'Vitao'
		WHEN MARCA = 'Manjar Coco Vegano em pó 50g Herbalmedica' THEN  'Wvegan'
		WHEN MARCA LIKE '%Hart''s Natural%' THEN 'Hart''s Natural'
		WHEN MARCA = 'Barra Choco ao Leite Zero Poliol com Pedaços de Pistache 75g' THEN  'LUCKAU'
		ELSE 'OUTROS'
	END AS MARCA_PRODUTO, * 

	FROM 
		ST_PRODUTO_PRECO_MV_DETALHADO_OFERTAS

UNION ALL

SELECT 
	'BEM-ESTAR' AS CATEGORIA
	,CASE
		WHEN MARCA LIKE '%Vitao%' THEN 'Vitao'	
		WHEN MARCA LIKE '%Luckau%' THEN 'Luckau'
		WHEN MARCA LIKE '%Haoma%' THEN 'Haoma'
		WHEN MARCA LIKE '%Da Magrinha%' THEN 'Da Magrinha'
		WHEN MARCA LIKE '%Puravida%' THEN 'Puravida'
		WHEN MARCA LIKE '%Bombay%' THEN 'Bombay'
		WHEN MARCA LIKE '%Flormel%' THEN 'Flormel'
		WHEN MARCA LIKE '%Fhom%' THEN 'Fhom'
		WHEN MARCA LIKE '%Bold Snacks%' THEN 'Bold Snacks'
		WHEN MARCA LIKE '%Mãe Terra%' THEN 'Mãe Terra'
		WHEN MARCA LIKE '%biO2%' THEN 'biO2'
		WHEN MARCA LIKE '%Suavipan%' THEN 'Suavipan'
		WHEN MARCA LIKE '%Belive%' THEN 'Belive'
		WHEN MARCA LIKE '%Schar%' THEN 'Schar'
		WHEN MARCA LIKE '%Warabu%' THEN 'Warabu'
		WHEN MARCA LIKE '%Mundo Verde%' THEN 'Mundo Verde'
		WHEN MARCA LIKE '%Stevita%' THEN 'Stevita'
		WHEN MARCA LIKE '%Chocolife%' THEN 'Chocolife'
		WHEN MARCA LIKE '%Sabor Alternati%' THEN 'Sabor Alternati'
		WHEN MARCA LIKE '%Essential Nutri%' THEN 'Essential Nutri'
		WHEN MARCA LIKE '%Wvegan%' THEN 'Wvegan'
		WHEN MARCA LIKE '%Mrs Taste%' THEN 'Mrs Taste'
		WHEN MARCA LIKE '%Mexidona%' THEN 'Mexidona'
		WHEN MARCA LIKE '%Mais Mu%' THEN 'Mais Mu'
		WHEN MARCA LIKE '%Life Mix%' THEN 'Life Mix'
		WHEN MARCA LIKE '%Eat Clean%' THEN 'Eat Clean'
		WHEN MARCA LIKE '%Engenho da Terr%' THEN 'Engenho da Terr'
		WHEN MARCA LIKE '%Caffeine Army%' THEN 'Caffeine Army'
		WHEN MARCA LIKE '%Papapá%' THEN 'Papapá'
		WHEN MARCA LIKE '%Pic-me%' THEN 'Pic-me'
		WHEN MARCA LIKE '%Canibal Inc%' THEN 'Canibal Inc'
		WHEN MARCA LIKE '%Aminna%' THEN 'Aminna'
		WHEN MARCA LIKE '%Grani Amici%' THEN 'Grani Amici'
		WHEN MARCA LIKE '%Fit Food%' THEN 'Fit Food'
		WHEN MARCA LIKE '%Mesmo!%' THEN 'Mesmo!'
		WHEN MARCA LIKE '%Atlhetica%' THEN 'Atlhetica'
		WHEN MARCA LIKE '%Integralmedica%' THEN 'Integralmedica'
		WHEN MARCA LIKE '%Casa Valentina%' THEN 'Casa Valentina'
		WHEN MARCA LIKE '%Vitapower%' THEN 'Vitapower'
		WHEN MARCA LIKE '%Naiak%' THEN 'Naiak'
		WHEN MARCA LIKE '%Tnuva%' THEN 'Tnuva'
		WHEN MARCA LIKE '%Roots to go%' THEN 'Roots to go'
		WHEN MARCA LIKE '%Mais Pura%' THEN 'Mais Pura'
		WHEN MARCA LIKE '%La Pianezza%' THEN 'La Pianezza'
		WHEN MARCA LIKE '%Desinchá%' THEN 'Desinchá'
		WHEN MARCA LIKE '%Super Nutrition%' THEN 'Super Nutrition'
		WHEN MARCA LIKE '%Nutrata%' THEN 'Nutrata'
		WHEN MARCA LIKE '%Mundo Verde Sel%' THEN 'Mundo Verde Sel'
		WHEN MARCA LIKE '%Castanharia%' THEN 'Castanharia'
		WHEN MARCA LIKE '%Alkimia%' THEN 'Alkimia'
		WHEN MARCA LIKE '%Oner%' THEN 'Oner'
		WHEN MARCA LIKE '%Naked Nuts%' THEN 'Naked Nuts'
		WHEN MARCA LIKE '%Nutrify%' THEN 'Nutrify'
		WHEN MARCA LIKE '%Espírito Cacau%' THEN 'Espírito Cacau'
		WHEN MARCA LIKE '%Vitafor%' THEN 'Vitafor'
		WHEN MARCA LIKE '%Dom Afonso%' THEN 'Dom Afonso'
		WHEN MARCA LIKE '%Banana Brasil%' THEN 'Banana Brasil'
		WHEN MARCA LIKE '%You Ka%' THEN 'You Ka'
		WHEN MARCA LIKE '%Super Vegan%' THEN 'Super Vegan'
		WHEN MARCA LIKE '%Snackout%' THEN 'Snackout'
		WHEN MARCA LIKE '%Amigos do Bem%' THEN 'Amigos do Bem'
		WHEN MARCA LIKE '%A Tal da Castan%' THEN 'A Tal da Castan'
		WHEN MARCA LIKE '%Uniagro%' THEN 'Uniagro'
		WHEN MARCA LIKE '%Monama%' THEN 'Monama'
		WHEN MARCA LIKE '%Chá Mais%' THEN 'Chá Mais'
		WHEN MARCA LIKE '%BetterPB%' THEN 'BetterPB'
		WHEN MARCA LIKE '%Betterlife%' THEN 'Betterlife'
		WHEN MARCA LIKE '%Beeva%' THEN 'Beeva'
		WHEN MARCA LIKE '%Alternativ%' THEN 'Alternativ'
		WHEN MARCA LIKE '%Nutrawell%' THEN 'Nutrawell'
		WHEN MARCA LIKE '%Nobrand%' THEN 'Nobrand'
		WHEN MARCA LIKE '%Mise%' THEN 'Mise'
		WHEN MARCA LIKE '%Koobi Kombucha%' THEN 'Koobi Kombucha'
		WHEN MARCA LIKE '%Konjac%' THEN 'Konjac'
		WHEN MARCA LIKE '%Darkness%' THEN 'Darkness'
		WHEN MARCA LIKE '%Ama Time%' THEN 'Ama Time'
		WHEN MARCA LIKE '%Advanced Nutrit%' THEN 'Advanced Nutrit'
		WHEN MARCA LIKE '%Sanavita%' THEN 'Sanavita'
		WHEN MARCA LIKE '%Power Focus%' THEN 'Power Focus'
		WHEN MARCA LIKE '%NotCo%' THEN 'NotCo'
		WHEN MARCA LIKE '%Magic Chocolate%' THEN 'Magic Chocolate'
		WHEN MARCA LIKE '%Linea%' THEN 'Linea'
		WHEN MARCA LIKE '%Estar Bem%' THEN 'Estar Bem'
		WHEN MARCA LIKE '%Danone%' THEN 'Danone'
		WHEN MARCA LIKE '%Da Roça%' THEN 'Da Roça'
		WHEN MARCA LIKE '%Brazô Alimentos%' THEN 'Brazô Alimentos'
		WHEN MARCA LIKE '%Plant Power%' THEN 'Plant Power'
		WHEN MARCA LIKE '%Mendoá%' THEN 'Mendoá'
		WHEN MARCA LIKE '%Leve Croc%' THEN 'Leve Croc'
		WHEN MARCA LIKE '%Holy Nuts%' THEN 'Holy Nuts'
		WHEN MARCA LIKE '%Good Soy%' THEN 'Good Soy'
		WHEN MARCA LIKE '%Chef Di Serio%' THEN 'Chef Di Serio'
		WHEN MARCA LIKE '%Wakas%' THEN 'Wakas'
		WHEN MARCA LIKE '%Valda%' THEN 'Valda'
		WHEN MARCA LIKE '%Fehe%' THEN 'Fehe'
		WHEN MARCA LIKE '%Chock%' THEN 'Chock'
		WHEN MARCA LIKE '%Chanical%' THEN 'Chanical'
		WHEN MARCA LIKE '%&Joy%' THEN '&Joy'
		WHEN MARCA LIKE '%Zen Foods%' THEN 'Zen Foods'
		WHEN MARCA LIKE '%Zaya%' THEN 'Zaya'
		WHEN MARCA LIKE '%Yamamotoyama%' THEN 'Yamamotoyama'
		WHEN MARCA LIKE '%Vitalin%' THEN 'Vitalin'
		WHEN MARCA LIKE '%Vital Âtman%' THEN 'Vital Âtman'
		WHEN MARCA LIKE '%Poder da Terra%' THEN 'Poder da Terra'
		WHEN MARCA LIKE '%Dose Coffee%' THEN 'Dose Coffee'
		WHEN MARCA LIKE '%Carob House%' THEN 'Carob House'
		WHEN MARCA LIKE '%Bananinha Palmi%' THEN 'Bananinha Palmi'
		WHEN MARCA LIKE '%Plant Pro%' THEN 'Plant Pro'
		WHEN MARCA LIKE '%Mare Chocolate%' THEN 'Mare Chocolate'
		WHEN MARCA LIKE '%Frontera%' THEN 'Frontera'
		WHEN MARCA LIKE '%Fini%' THEN 'Fini'
		WHEN MARCA LIKE '%Fiber%' THEN 'Fiber'
		WHEN MARCA LIKE '%Beladri%' THEN 'Beladri'
		WHEN MARCA LIKE '%Amma Chocolate%' THEN 'Amma Chocolate'
		WHEN MARCA LIKE '%True Source%' THEN 'True Source'
		WHEN MARCA LIKE '%Tivva%' THEN 'Tivva'
		WHEN MARCA LIKE '%Terra Moriá%' THEN 'Terra Moriá'
		WHEN MARCA LIKE '%Organique%' THEN 'Organique'
		WHEN MARCA LIKE '%Omix%' THEN 'Omix'
		WHEN MARCA LIKE '%Nutríssima%' THEN 'Nutríssima'
		WHEN MARCA LIKE '%Moderação%' THEN 'Moderação'
		WHEN MARCA LIKE '%Harts Natural%' THEN 'Harts Natural'
		WHEN MARCA LIKE '%Fresh Nutrition%' THEN 'Fresh Nutrition'
		WHEN MARCA LIKE '%Dobro%' THEN 'Dobro'
		WHEN MARCA LIKE '%Crilancha%' THEN 'Crilancha'
		WHEN MARCA LIKE '%Copra Coco%' THEN 'Copra Coco'
		WHEN MARCA LIKE '%Sweet Jelly%' THEN 'Sweet Jelly'
		WHEN MARCA LIKE '%Planttcê%' THEN 'Planttcê'
		WHEN MARCA LIKE '%Pipoca do Johnn%' THEN 'Pipoca do Johnn'
		WHEN MARCA LIKE '%Ocean Drop%' THEN 'Ocean Drop'
		WHEN MARCA LIKE '%Natures Heart%' THEN 'Natures Heart'
		WHEN MARCA LIKE '%Mundo Verde Eli%' THEN 'Mundo Verde Eli'
		WHEN MARCA LIKE '%Mais Mu Perform%' THEN 'Mais Mu Perform'
		WHEN MARCA LIKE '%Macrokant%' THEN 'Macrokant'
		WHEN MARCA LIKE '%Kim Zucateli%' THEN 'Kim Zucateli'
		WHEN MARCA LIKE '%Iridium Labs%' THEN 'Iridium Labs'
		WHEN MARCA LIKE '%Hypera Pharma%' THEN 'Hypera Pharma'
		WHEN MARCA LIKE '%Ecobio%' THEN 'Ecobio'
		WHEN MARCA LIKE '%Chá Prenda%' THEN 'Chá Prenda'
		WHEN MARCA LIKE '%100% Você%' THEN '100% Você'
		WHEN MARCA LIKE '%Zucca Cogumelos%' THEN 'Zucca Cogumelos'
		WHEN MARCA LIKE '%Ws Naturais%' THEN 'Ws Naturais'
		WHEN MARCA LIKE '%Onvittá%' THEN 'Onvittá'
		WHEN MARCA LIKE '%Natures Heart%' THEN 'Natures Heart'
		WHEN MARCA LIKE '%Mellow%' THEN 'Mellow'
		WHEN MARCA LIKE '%Jungle%' THEN 'Jungle'
		WHEN MARCA LIKE '%Ganic%' THEN 'Ganic'
		WHEN MARCA LIKE '%Dêvi%' THEN 'Dêvi'
		WHEN MARCA LIKE '%Crystal Sweet%' THEN 'Crystal Sweet'
		WHEN MARCA LIKE '%Café Utam%' THEN 'Café Utam'
		WHEN MARCA LIKE '%Bioroots%' THEN 'Bioroots'
		WHEN MARCA LIKE '%Airon%' THEN 'Airon'
		WHEN MARCA LIKE '%Vida Veg%' THEN 'Vida Veg'
		WHEN MARCA LIKE '%Upnutri%' THEN 'Upnutri'
		WHEN MARCA LIKE '%Sesamo Real%' THEN 'Sesamo Real'
		WHEN MARCA LIKE '%QueenNut%' THEN 'QueenNut'
		WHEN MARCA LIKE '%Piracanjuba%' THEN 'Piracanjuba'
		WHEN MARCA LIKE '%Pinati%' THEN 'Pinati'
		WHEN MARCA LIKE '%Pholias%' THEN 'Pholias'
		WHEN MARCA LIKE '%Nutraway%' THEN 'Nutraway'
		WHEN MARCA LIKE '%Naturalis%' THEN 'Naturalis'
		WHEN MARCA LIKE '%Lowçucar%' THEN 'Lowçucar'
		WHEN MARCA LIKE '%Kur Kur%' THEN 'Kur Kur'
		WHEN MARCA LIKE '%Kur%' THEN 'Kur Kur'
		WHEN MARCA LIKE '%Kur My Home Spa%' THEN 'Kur My Home Spa'
		WHEN MARCA LIKE '%Java Chocolates%' THEN 'Java Chocolates'
		WHEN MARCA LIKE '%Gummy%' THEN 'Gummy'
		WHEN MARCA LIKE '%Gaab%' THEN 'Gaab'
		WHEN MARCA LIKE '%Fumel%' THEN 'Fumel'
		WHEN MARCA LIKE '%Bifum%' THEN 'Bifum'
		WHEN MARCA LIKE '%Agtal%' THEN 'Agtal'
		WHEN MARCA LIKE '%Ayurveda%' THEN 'Kim Zucateli'
		WHEN MARCA LIKE '%DESINCHÁ%' THEN  'Desinchá'
		WHEN MARCA LIKE 'DESIN%' THEN  'Desinchá'
		WHEN MARCA LIKE 'Chá da Frozen Frutas Vermelhas 15sch 22,5g' THEN 'Desinchá'
		WHEN MARCA = 'Geleia Zero Uva 180g' THEN  'Vitao'
		WHEN MARCA = 'Manjar Coco Vegano em pó 50g Herbalmedica' THEN  'Wvegan'
		WHEN MARCA LIKE '%Hart''s Natural%' THEN 'Hart''s Natural'
		WHEN MARCA = 'Barra Choco ao Leite Zero Poliol com Pedaços de Pistache 75g' THEN  'LUCKAU'
		ELSE 'OUTROS'
	END AS MARCA_PRODUTO, * 

	FROM 
		ST_PRODUTO_PRECO_MV_DETALHADO_OUTROS

)
-- PREÇOS MUNDO VERDE SITE --
SELECT DISTINCT
	
	MARCA_PRODUTO
	, A.CATEGORIA
	, CASE WHEN ISNULL(A.PRECO_ATUAL,B.PRECO_ATUAL) IS NULL THEN 'PRODUTO_INDISPONIVEL' ELSE 'PRODUTO_DISPONIVEL' END											AS DISPONIBILIDADE
	, A.ID																																						AS ID_PRODUTO	
	, A.MARCA																																					AS DS_PRODUTO
	, ISNULL(A.PRECO_ATUAL,B.PRECO_ATUAL)																														AS PRECO_PRODUTO
	, ISNULL(A.PRECO_ANTERIOR,ISNULL(B.PRECO_ANTERIOR, A.PRECO_ATUAL))																							AS PRECO_ANTERIOR
	, CAST(ISNULL((((ISNULL(A.PRECO_ANTERIOR,B.PRECO_ANTERIOR) * 1.0)	/ (ISNULL(A.PRECO_ATUAL, B.PRECO_ATUAL) * 1.0)) * 1.0)-1,0) AS decimal (3,2)) * 100		AS '%_DESCONTO'
	, A.DATA_HORA_SCRAPE

FROM 
	TRATAMENTO_MARCA A
LEFT JOIN
	ST_PRODUTO_PRECO_MV_DETALHADO_SEARCH B
	ON B.MARCA = A.MARCA

ORDER BY PRECO_PRODUTO DESC



